server.port: 8090
# logging.config: classpath:logback/logback.xml
logging:
    level:
        org.hibernate.type.descriptor.sql: trace

spring:
    data:
        rest:
            base-path: /rest
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    h2:
        console:
            enabled: true
            path: /console
    datasource:
        url: jdbc:h2:mem:sssdb
        driver-class-name: org.h2.Driver
        username: jistol
        password: 1234
    jpa:
        hibernate:
            format_sql: true
            ddl-auto: create-drop
        show_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

