server.port: 8090
# logging.config: classpath:logback/logback.xml
logging:
    level:
        org.hibernate.type.descriptor.sql: trace

spring:
    data:
        rest:
            base-path: /rest
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    h2:
        console:
            enabled: true
            path: /console
    datasource:
        url: jdbc:h2:mem:sssdb
        driver-class-name: org.h2.Driver
        username: jistol
        password: 1234
    jpa:
        hibernate:
            format_sql: true
            ddl-auto: create-drop
        show_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

initialize-data:
    survey-list:
    - name: 테스트 설문
      description: 테스트 설문 입니다.
      question:
          name: 질문입니다.
          description: 테스트 설문 질문입니다. <br/> 질문에 대한 설명이 여기에 붙습니다. <br/> 여러줄을 넣을 수 있습니다.
          question-item-list:
          - description: 첫 번째 질문입니다.
          - description: 두 번째 질문입니다.
          - description: 세 번째 질문입니다.
          - description: 네 번째 질문입니다.
    - name: "주제 발표 설문"
      description: "기획_홈 파트에서 진행한 주제발표에 대한 설문입니다."
      question:
          name: "주제 발표 설문 2019-12-09"
          description: "<ul><li>주제 발표 로테이션간 느낀점을 기준으로 아래 설문을 작성 부탁드립니다.</li><li>아래 주제에 대해 동의할 수록 높은 점수를, 동의하지 않을 수록 낮은 점수를 체크하면 됩니다.</li><li>설문은 총 10문항으로 설문 총점 평균이 700점 이상일 경우 다음 주제 발표 로테이션을 진행합니다.</li><li>설문 작성자에 대한 확인 및 식별은 불가능하니 소신껏 작성 부탁드립니다.</li></ul>"
          question-item-list:
          - description: "1. 나는 우리 파트에서 눈치보지 않고 자유롭게 의견을 낼 수 있습니다."
          - description: "2. 나 외의 다른 파트원들은 모두 눈치보지 않고 자유롭게 의견을 내고 있다고 생각합니다."
          - description: "3. 나는 이번 주제 발표를 준비과정이 부담스럽지 않았습니다."
          - description: "4. 나는 다음 주제 발표로 하고 싶은 주제가 있거나 계획이 있습니다."
          - description: "5. 나의 발표가 타 파트원들에게 도움이 되었다고 생각합니다."
          - description: "6. 타 파트원들의 발표가 나에게 도움이 되었습니다."
          - description: "7. 나는 발표준비과정 및 발표로 인해 발전했다고 생각합니다."
          - description: "8. 다음 발표는 처음보다 더 잘(또는 편하게) 할 수 있다고 생각합니다."
          - description: "9. 이런 행위가 우리 파트에 도움이 된다 생각합니다."
          - description: "10. 주제발표준비를 위해 업무외 시간을 일정수준 투자 할 수 있다고 생각합니다."
