server.port: 8090
# logging.config: classpath:logback/logback.xml
logging:
    level:
        org.hibernate.type.descriptor.sql: trace

spring:
    data:
        rest:
            base-path: /rest
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    h2:
        console:
            enabled: true
            path: /console
    datasource:
        url: jdbc:h2:mem:sssdb
        driver-class-name: org.h2.Driver
        username: jistol
        password: 1234
    jpa:
        hibernate:
            format_sql: true
            ddl-auto: create-drop
        show_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

initialize-data:
    survey-list:
    - name: 테스트 설문
      description: 테스트 설문 입니다.
      question:
          name: 질문입니다.
          question-item-list:
          - description: 첫 번째 질문입니다.
          - description: 두 번째 질문입니다.
          - description: 세 번째 질문입니다.
          - description: 네 번째 질문입니다.
